spring:
  main:
    banner-mode: off

logging:
  level:
    '[com.mahitotsu.arges.api.config]':  info
    '[com.mahitotsu.arges.api.repository]':  debug
    '[com.zaxxer.hikari]':  info

mahitotsu:
  dsql:
    endpoints:
      - 4iabtwnq2j55iez4j4bkykghgm.dsql.us-east-1.on.aws
      - s4abtwnq2jebk7aj6vhlsb2coi.dsql.us-east-2.on.aws
    connection:
      properties:
        sslmode: require
        loginTimeout: 5
        connectionTimeout: 2
    token:
      expirationSeconds: 30